DDaiso/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import product.views

urlpatterns = [
    # path('', product.views.ProductListView.as_view(), name='home'),
    path('', product.views.list_product, name='home'),
    path('product/', include('product.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from product import views
from product.views import ProductListView, ProductCreateView, ProductDetailView, ProductUpdateView, ProductDeleteView

app_name = 'product'

urlpatterns = [
    path('list/', ProductListView.as_view(), name='list'),  # product:list
    path('list2/', views.list_product, name='list2'),  # product:list2
    path('detail/<int:pk>/', ProductDetailView.as_view(), name='detail'),  # product:detail
    path('detail2/<int:pk>/', views.detail_product, name='detail2'),  # product:detail2
    path('add/', ProductCreateView.as_view(), name='add'),  # product:add
    path('add2/', views.create_product, name='add2'),  # product:add2
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit'),  # product:edit
    path('edit2/<int:pk>/', views.update_product, name='edit2'),  # product:edit2
    path('remove/<int:pk>/', ProductDeleteView.as_view(), name='remove'),  # product:remove
    path('remove2/<int:pk>/', views.delete_product, name='remove2'),  # product:remove
    path('product/<int:product_pk>/add2_review/', views.add2_review, name='add2_review'),  # product:add2_review
    path('product/<int:product_pk>/edit2_review/<int:review_pk>/', views.edit2_review, name='edit2_review'),  # product:edit2_review
    path('product/<int:product_pk>/remove2_review/<int:review_pk>/', views.remove2_review, name='remove2_review'),  # product:remove2_review
]

product/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.shortcuts import resolve_url


class Product(models.Model):
    name = models.CharField(max_length=20)
    price = models.IntegerField(validators=[MinValueValidator(0)])  # PositiveIntegerField()
    image = models.ImageField(upload_to='images/%Y/%m/%d/', blank=True, null=True)

    def __str__(self):
        return f'{self.name}: {self.price}원'  # 이름: 가격원

    def get_absolute_url(self):  # 모델 하나를 구하는 절대 주소 구하자
        return resolve_url('product:detail', pk=self.id)


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    contents = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.contents}'

    class Meta:
        ordering = ['-updated_at']

product/forms.py
from django import forms

from product.models import Product, Review


class ProductCreationForm(forms.ModelForm):
    price = forms.IntegerField(label='가격', widget=forms.NumberInput)

    class Meta:
        model = Product
        fields = ['name', 'price', 'image']  # '__all__'

    def save(self, commit=True):
        new_product = Product.objects.create(
            name=self.cleaned_data.get('name'),  # 사용자가 입력한 내용을 clean_name()하고 깨끗해진 것 가져오자
            price=self.cleaned_data.get('price'),  # 사용자가 입력한 내용을 clean_price()하고 깨끗해진 것 가져오자
            image=self.cleaned_data.get('image'),
        )
        return new_product


class ProductChangeForm(forms.ModelForm):
    price = forms.IntegerField(label='가격', widget=forms.NumberInput)

    class Meta:
        model = Product
        fields = ['name', 'price', 'image']  # '__all__'


class ReviewCreationForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=Product.objects.all(), widget=forms.HiddenInput)  # product 선택창은 숨기자
    contents = forms.CharField(label="댓글", widget=forms.TextInput)  # 한줄짜리 <input type="text">로 하자

    class Meta:
        model = Review
        fields = ['product', 'contents']


class ReviewChangeForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=Product.objects.all(), widget=forms.HiddenInput)  # product 선택창은 숨기자
    contents = forms.CharField(label="댓글", widget=forms.TextInput)  # 한줄짜리 <input type="text">로 하자

    class Meta:
        model = Review
        fields = ['product', 'contents']

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from product.forms import ProductCreationForm, ProductChangeForm, ReviewCreationForm, ReviewChangeForm
from product.models import Product, Review


class ProductListView(ListView):
    model = Product
    # 'product_list.html', {'product_list': Product.objects.all()}
    paginate_by = 3


class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(CreateView):
    model = Product
    fields = ['name', 'price']  # '__all__'
    template_name_suffix = '_create'  # product_form.html -> product_create.html
    success_url = reverse_lazy('product:list')  # 만들기 성공하면 이동할 url 이름


class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name', 'price']  # '__all__'
    template_name_suffix = '_update'
    # success_url = reverse_lazy('product:list')  # 수정 성공하면 이동할 url 이름


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('product:list')


def list_product(request):
    product_list = Product.objects.all()  # product 다 가져오자
    context = {'product_list': product_list}
    return render(request, 'product/product_list.html', context)


def detail_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {'product': product}
    return render(request, 'product/product_detail.html', context)


def create_product(request):
    if request.method == 'POST':  # 사용자가 입력하고 버튼 눌렀을 때
        form = ProductCreationForm(request.POST, request.FILES)  # form 가져오자    주의! files는 request.FILES로 꼭 지정해줘야 함
        if form.is_valid():
            form.save()  # new_product 저장하자
        return redirect('product:list2')
    else:  # 빈 폼
        form = ProductCreationForm()
    return render(request, 'product/product_create.html', {'form': form})


def update_product(request, pk):
    product = get_object_or_404(Product, pk=pk)  # pk에 해당하는 product 가져오자
    if request.method == 'POST':  # 사용자가 입력하고 버튼 눌렀을 때
        form = ProductChangeForm(request.POST, request.FILES,
                                 instance=product)  # form 가져오자    주의! files는 request.FILES로 꼭 지정해줘야 함
        if form.is_valid():
            form.save()  # 수정한 product 저장하자
        return redirect('product:list2')
    else:
        form = ProductChangeForm(instance=product)
    return render(request, 'product/product_update.html', {'form': form, 'product': product})


def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk)  # pk에 해당하는 product 가져오자
    if request.method == 'POST':  # 사용자가 입력하고 버튼 눌렀을 때
        product.delete()  # product 삭제하자
        return redirect('product:list2')
    else:
        pass
    return render(request, 'product/product_confirm_delete.html', {'product': product})


def add2_review(request, product_pk):
    if request.method == 'POST':
        form = ReviewCreationForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('product:detail2', pk=product_pk)
    else:
        product = get_object_or_404(Product, pk=product_pk)
        initial = {'product': product}
        form = ReviewCreationForm(initial=initial)
        context = {'form': form, 'product': product}
    return render(request, 'product/review_create.html', context)


def edit2_review(request, product_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.method == 'POST':
        form = ReviewChangeForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
        return redirect('product:detail2', pk=product_pk)
    else:
        form = ReviewChangeForm(instance=review)
        context = {'form': form}
    return render(request, 'product/review_update.html', context)


def remove2_review(request, product_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)  # pk에 해당하는 review 가져오자
    if request.method == 'POST':  # 사용자가 입력하고 버튼 눌렀을 때
        review.delete()  # review 삭제하자
        return redirect('product:detail2', pk=product_pk)
    else:
        pass
    return render(request, 'product/review_confirm_delete.html', {'review': review})

product/templates/product/product_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Remove Product{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="alert alert-danger">
            [{{ product }}] 상품을 진짜 지우겠습니까?
            <div>
                {% if product.image %}
                    <img src="{{ product.image.url }}" alt="{{ product.name }}" class="image-detail">
                {% else %}
                    없음
                {% endif %}
            </div>
            <hr>
            <ul>
                {% if product.review_set.count > 0 %}
                    {% for review in product.review_set.all %}
                        <li>{{ review }}</li>
                    {% endfor %}
                {% endif %}
            </ul>
        </div>

        <input type="submit" value="진짜 삭제" class="btn btn-danger">
        <input type="button" value="지우지마" onclick="history.back();" class="btn btn-light">
    </form>
{% endblock %}

product/templates/product/product_create.html
{% extends 'base.html' %}

{% block title %}Add Product{% endblock %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" class="btn btn-success">
</form>
{% endblock %}

product/templates/product/product_detail.html
{% extends 'base.html' %}

{% block title %}Product Detail{% endblock %}

{% block content %}
    <h1>{{ product.name }}</h1>
    {% if product.image %}
        <img src="{{ product.image.url }}" alt="{{ product.name }}" class="image-detail">
    {% else %}
        없음
    {% endif %}<br>
    {{ product.price }}원
    <hr>
    <ul>
        {% if product.review_set.count > 0 %}
            {% for review in product.review_set.all %}
                <li>{{ review }}
                    <a href="{% url 'product:edit2_review' product_pk=product.id review_pk=review.id  %}" class="btn btn-primary btn-sm">EDIT</a>
                    <a href="{% url 'product:remove2_review' product_pk=product.id review_pk=review.id  %}" class="btn btn-danger btn-sm">REMOVE</a>
                </li>
            {% endfor %}
        {% endif %}
    </ul>
    <a href="{% url 'product:add2_review' product_pk=product.id %}" class="btn btn-success btn-sm">Add Review</a>
    <p><a href="{% url 'product:list2' %}" class="btn btn-warning">Go to Product List</a></p>
{% endblock %}

product/templates/product/product_list.html
{% extends 'base.html' %}

{% block title %}Product List{% endblock %}

{% block content %}
<div class="btn-group">
    <a href="{% url 'product:add2' %}" class="btn btn-success">Add Product</a>
</div>

<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>제품사진</th>
        <th>제품명</th>
        <th>가격</th>
        <th>EDIT</th>
        <th>REMOVE</th>
    </tr>
    </thead>
    <tbody>
    {% for product in product_list %}
        <tr>
            <td class="align-middle">{{ forloop.counter }}</td>
        <td class="align-middle text-center">
            {% if product.image %}
                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="image-list">
            {% else %}
                없음
            {% endif %}
        </td>
            <td class="align-middle"><a href="{% url 'product:detail2' pk=product.id %}">{{ product.name }} (상품평: {{ product.review_set.count }})</a></td>
            <td class="align-middle">{{ product.price }}원</td>
            <td class="align-middle"><a href="{% url 'product:edit2' pk=product.id %}" class="btn btn-primary">EDIT</a></td>
            <td class="align-middle"><a href="{% url 'product:remove2' pk=product.id %}" class="btn btn-danger">REMOVE</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block pagination %}
    {% if is_paginated %}
        <ul class="pagination justify-content-center pagination-sm">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
            {% endif %}

            {% for object in page_obj.paginator.page_range %}
                {% if page_obj.number != forloop.counter %}
                    <li class="page-item">
                        <a class="page-link" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">{{ forloop.counter }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Next</a>
                </li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

product/templates/product/product_update.html
{% extends 'base.html' %}

{% block title %}Edit Product{% endblock %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Edit" class="btn btn-primary">
    <hr>
    <ul>
        {% if product.review_set.count > 0 %}
            {% for review in product.review_set.all %}
                <li>{{ review }}
                    <a href="{% url 'product:edit2_review' product_pk=product.id review_pk=review.id  %}" class="btn btn-primary btn-sm">EDIT</a>
                    <a href="{% url 'product:remove2_review' product_pk=product.id review_pk=review.id  %}" class="btn btn-danger btn-sm">REMOVE</a>
                </li>
            {% endfor %}
        {% endif %}
    </ul>
</form>
{% endblock %}

product/templates/product/review_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Remove Review{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="alert alert-danger">
            [{{ review }}] 상품평을 진짜 지우겠습니까?
        </div>

        <input type="submit" value="진짜 삭제" class="btn btn-danger">
        <input type="button" value="지우지마" onclick="history.back();" class="btn btn-light">
    </form>
{% endblock %}

product/templates/product/review_create.html
{% extends 'base.html' %}

{% block title %}Add Review{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" class="btn btn-success">
</form>
{% endblock %}

product/templates/product/review_update.html
{% extends 'base.html' %}

{% block title %}Edit Review{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Edit" class="btn btn-primary">
</form>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}

    {% block pagination %}
    {% endblock %}

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>